# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Why UniformGraphQL?'
  link: '/why-uniform-graphql'
- label: 'Get Started'
  link: '/get-started'
- label: Types
  items:
    - label: 'Scalars'
      link: '/types/scalars'
    - label: 'Nullability'
      link: '/types/nullability'
    - label: 'Enums'
      link: '/types/enums'
    - label: 'Input & Output Types'
      link: '/types/input-and-output-types'
    - label: 'Objects'
      link: '/types/objects'
    - label: 'Lists'
      link: '/types/lists'
    - label: 'Interfaces'
      link: '/types/interfaces'
    - label: 'Unions'
      link: '/types/unions'
    - label: 'Input Objects'
      link: '/types/input-objects'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/whats-good/uniform-graphql
