# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Quickstart'
  link: '/quickstart'
- label: 'Motivation'
  link: '/motivation'
- label: 'Philosophy'
  link: '/philosophy'
- label: Types
  items:
    - label: 'Built-in Scalars'
      link: '/types/built-in-scalars'
    - label: 'Custom Scalars'
      link: '/types/custom-scalars'
    - label: 'Nullability'
      link: '/types/nullability'
    - label: 'Enums'
      link: '/types/enums'
    - label: 'Input & Output Types'
      link: '/types/input-and-output-types'
    - label: 'Objects'
      link: '/types/objects'
    - label: 'Lists'
      link: '/types/lists'
    - label: 'Input Objects'
      link: '/types/input-objects'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/whats-good/uniform-graphql
